### PR TITLE
Add loading state for show/hide loading spinner

### LINKED ISSUE #14: Images loaded, loader doesn't disappear.
Hi! I have a problem with this component. the loading gif/placeholder isn't disappearing once the image has loaded.

My steps:
- Web loads.
- Async content API request starts.
- When the content is ready, creates a few ReactImageAppear elements with the API provided src.
- Loader gif appears.
- When the image loads, it's placed behind the loader gif.
- Loading gif doesn't disappear.

### PR DESCRIPTION
**Pull request by pcw0002**
This should resolve #14 and #6

### CODE REVIEW

**Comment by ArunMichaelDsouza** [comment]
Hi @pcw0002, thanks again for the PR. If possible, can you please verify whether this change fixes the bug reported [here](https://github.com/ArunMichaelDsouza/react-image-appear/issues/14#issuecomment-634096559). Thank you!

**Comment by pcw0002** [comment]
@ArunMichaelDsouza Of course. I added a test and below are two GIF's that show current master behavior and my fix (added a 4 second timeout to the imageOnLoad() function to help see the functionality better, removed after video).


Current master/production behavior (master.gif):
master

This PR behavior (fix.gif):
fix

**Comment by ArunMichaelDsouza** [comment]
Hi @pcw0002, this is great! Thanks again for your efforts. I'll publish this fix soon.

**Comment by ArunMichaelDsouza** [comment]
The changes are now available in [v1.3.24](https://github.com/ArunMichaelDsouza/react-image-appear/releases/tag/v1.3.24).

**Pull request merged**
